version: '2.4'
services:
  mifosx:
    build:
      context: ./mifos
      dockerfile: Dockerfile
    container_name: mifosx
    restart: always
    ports:
      - '8443:8443'
    networks:
      - app-tier
    depends_on:
      mifos-db-server:
        condition: service_healthy
      # mifos-sms-server:
      #   condition: service_healthy
  mifos-db-server:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mifos-db
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    healthcheck:
      test: mysqladmin --user=root --password=mysql ping -h localhost
      interval: 5s
      retries: 20
    networks:
      - app-tier
  # mifos-sms-server:
  #   build:
  #     context: ./activemq
  #     dockerfile: Dockerfile
  #   container_name: mifosx-sms
  #   restart: always
  #   environment:
  #     ACTIVEMQ_CONFIG_MINMEMORY: 512
  #     ACTIVEMQ_CONFIG_MAXMEMORY: 1024
  #   healthcheck:
  #     test: 'curl -u admin:admin -s http://localhost:8161/admin'
  #     interval: 5s
  #     retries: 20
  #   networks:
  #     - app-tier
networks:
  app-tier:
    driver: bridge
